services:
  fastapi:
    build:
      context: .
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/healthz || (echo 'Healthcheck failed' && exit 1)"]
      interval: 10s
      timeout: 60s
      retries: 5
    environment: 
      - DB_PATH=postgresql://postgres:postgrespassword@postgres:5432/tasksdb  # Removed unnecessary quotes
    depends_on:
      postgres:
        condition: service_healthy  # Added health check condition for PostgreSQL
    ports: 
      - "8000:8000"

  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tasksdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Ensuring the nginx.conf file is correctly mapped
    depends_on:
      - fastapi

volumes:
  pgdata:
