on:
  push:
    branches:
      - '**'

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Docker compose config
        run: docker compose config

      - name: Verify Dockerfile
        run: |
          DOCKERFILE=Dockerfile
          if [[ ! -f "$DOCKERFILE" ]]; then
            echo "❌ Dockerfile not found!"
            exit 1
          fi

          # Check number of stages
          STAGE_COUNT=$(grep -c '^FROM' "$DOCKERFILE")
          echo "✅ Found $STAGE_COUNT stages in the Dockerfile."
          if [[ $STAGE_COUNT -lt 2 ]]; then
            echo "❌ Dockerfile must have at least 2 stages (multi-stage build required)."
            exit 1
          fi

          # Check base image
          if ! grep -q '^FROM python:3.11-buster' "$DOCKERFILE"; then
            echo "❌ Base image is not 'python:3.11-buster'"
            exit 1
          else
            echo "✅ Base image is 'python:3.11-buster'"
          fi

          # Check WORKDIR
          if ! grep -q '^WORKDIR /app' "$DOCKERFILE"; then
            echo "❌ WORKDIR is not set to '/app'"
            exit 1
          else
            echo "✅ WORKDIR is set to '/app'"
          fi

  integration-test:
    timeout-minutes: 10
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start services using Docker Compose
        run: docker compose up -d --wait

      - name: Run API Integration Tests
        run: |
          chmod +x ./tests/api_tests.sh
          ./tests/api_tests.sh

      - name: Shutdown services
        run: docker compose down

  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    needs:
      - integration-test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          project_id: 'cs1660project-451418'  # Update with your project ID
          workload_identity_provider: "projects/1094858932747/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions@curious-framing-451620-c2.iam.gserviceaccount.com"

      - name: Authenticate Docker with Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          gcloud auth list  # Debugging: Verify that authentication works

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push the Image
        uses: docker/build-push-action@v6
        with:
          context: ./ 
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/cs1660project-451418/first-artifact/fastapi-server:v2
