name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose configuration
        run: docker compose config

      - name: Verify Dockerfile
        run: |
          DOCKERFILE=Dockerfile
          if [[ ! -f "$DOCKERFILE" ]]; then
            echo "❌ Dockerfile not found!"
            exit 1
          fi

          # Check if Dockerfile has multiple stages
          STAGE_COUNT=$(grep -c '^FROM' "$DOCKERFILE")
          echo "✅ Found $STAGE_COUNT stages in the Dockerfile."
          if [[ $STAGE_COUNT -lt 2 ]]; then
            echo "❌ Dockerfile must have at least 2 stages."
            exit 1
          fi

          # Check base image
          if ! grep -qE '^FROM python:(3.10|3.11)-buster' "$DOCKERFILE"; then
            echo "❌ Base image must be Python 3.10+ with Buster."
            exit 1
          else
            echo "✅ Valid base image detected."
          fi

  integration-test:
    runs-on: ubuntu-latest
    needs: docker-check
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Start services using Docker Compose
        run: docker compose up -d --wait

      - name: Run API Integration Tests
        run: |
          chmod +x ./tests/api_tests.sh
          ./tests/api_tests.sh

      - name: Shutdown services
        run: docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: integration-test
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: "curious-framing-451620-c2"  # Replace with your actual GCP Project ID
          workload_identity_provider: "projects/1094858932747/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions@curious-framing-451620-c2.iam.gserviceaccount.com"

      - name: Authenticate Docker with Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/curious-framing-451620-c2/my-docker-repo/fastapi-server:v2
